/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HTTPError
 */
export interface HTTPError {
    /**
     * 
     * @type {object}
     * @memberof HTTPError
     */
    detail?: object;
    /**
     * 
     * @type {string}
     * @memberof HTTPError
     */
    message?: string;
}

/**
 * Check if a given object implements the HTTPError interface.
 */
export function instanceOfHTTPError(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HTTPErrorFromJSON(json: any): HTTPError {
    return HTTPErrorFromJSONTyped(json, false);
}

export function HTTPErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): HTTPError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'detail': !exists(json, 'detail') ? undefined : json['detail'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function HTTPErrorToJSON(value?: HTTPError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'detail': value.detail,
        'message': value.message,
    };
}

