/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageCreatedOut
 */
export interface ImageCreatedOut {
    /**
     * 
     * @type {string}
     * @memberof ImageCreatedOut
     */
    aiVersion?: ImageCreatedOutAiVersionEnum;
    /**
     * The type of enhancement to apply to the image. PROPERTY or PROPERTY_USA is used with AI version < 4.0, for >= 4.0 use WARM, NEUTRAL, or AUTHENTIC.
     * @type {string}
     * @memberof ImageCreatedOut
     */
    enhanceType?: ImageCreatedOutEnhanceTypeEnum;
    /**
     * Whether the sky replacement feature was enabled for the image.
     * @type {boolean}
     * @memberof ImageCreatedOut
     */
    skyReplacement?: boolean;
    /**
     * Whether the vertical correction feature was enabled for the image.
     * @type {boolean}
     * @memberof ImageCreatedOut
     */
    verticalCorrection?: boolean;
    /**
     * Correct any lens distortion in the image.
     * @type {boolean}
     * @memberof ImageCreatedOut
     */
    lensCorrection?: boolean;
    /**
     * The amount of contrast boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageCreatedOut
     */
    contrastBoost?: ImageCreatedOutContrastBoostEnum;
    /**
     * The amount of brightness boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageCreatedOut
     */
    brightnessBoost?: ImageCreatedOutBrightnessBoostEnum;
    /**
     * The amount of saturation to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageCreatedOut
     */
    saturationLevel?: ImageCreatedOutSaturationLevelEnum;
    /**
     * The amount of sharpening to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageCreatedOut
     */
    sharpenLevel?: ImageCreatedOutSharpenLevelEnum;
    /**
     * The amount of denoising to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageCreatedOut
     */
    denoiseLevel?: ImageCreatedOutDenoiseLevelEnum;
    /**
     * The amount of clarity to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageCreatedOut
     */
    clarityLevel?: ImageCreatedOutClarityLevelEnum;
    /**
     * Whether to blur any faces or license plates in the image.
     * @type {boolean}
     * @memberof ImageCreatedOut
     */
    privacy?: boolean;
    /**
     * Whether to pull the windows in the image (used with AI version >= 4.0).
     * @type {boolean}
     * @memberof ImageCreatedOut
     */
    windowPull?: boolean;
    /**
     * The type of clouds in the new sky to replace the original sky with. Options include: CLEAR, LOW_CLOUD, HIGH_CLOUD
     * @type {string}
     * @memberof ImageCreatedOut
     */
    cloudType?: ImageCreatedOutCloudTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageCreatedOut
     */
    skySaturationLevel?: ImageCreatedOutSkySaturationLevelEnum;
    /**
     * The amount of internal contrast boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageCreatedOut
     */
    contrastBoostInternal?: ImageCreatedOutContrastBoostInternalEnum;
    /**
     * The amount of external contrast boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageCreatedOut
     */
    contrastBoostExternal?: ImageCreatedOutContrastBoostExternalEnum;
    /**
     * The amount of external brightness boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageCreatedOut
     */
    brightnessBoostInternal?: ImageCreatedOutBrightnessBoostInternalEnum;
    /**
     * The amount of external brightness boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageCreatedOut
     */
    brightnessBoostExternal?: ImageCreatedOutBrightnessBoostExternalEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageCreatedOut
     */
    imageId?: string;
    /**
     * The user ID of the user who uploaded (owns) the image.
     * @type {string}
     * @memberof ImageCreatedOut
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageCreatedOut
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageCreatedOut
     */
    imageName?: string;
    /**
     * The image type for the image.
     * @type {string}
     * @memberof ImageCreatedOut
     */
    imageType?: string;
    /**
     * The date the image was registered with Autoenhance.
     * @type {number}
     * @memberof ImageCreatedOut
     */
    dateAdded?: number;
    /**
     * The detected scene of the image i.e garden, patio, kitchen, etc.
     * @type {string}
     * @memberof ImageCreatedOut
     */
    scene?: string;
    /**
     * The status of the order.
     * @type {string}
     * @memberof ImageCreatedOut
     */
    readonly status?: ImageCreatedOutStatusEnum;
    /**
     * Whether the image has been enhanced.
     * @type {boolean}
     * @memberof ImageCreatedOut
     */
    enhanced?: boolean;
    /**
     * Whether the image has an error.
     * @type {boolean}
     * @memberof ImageCreatedOut
     */
    error?: boolean;
    /**
     * Whether image has been already downloaded and paid for.
     * @type {boolean}
     * @memberof ImageCreatedOut
     */
    downloaded?: boolean;
    /**
     * A rating between 0 and 5 on how good the image enhancmeent. Higher is better.
     * @type {number}
     * @memberof ImageCreatedOut
     */
    rating?: number;
    /**
     * Whether the image is a 360° image
     * @type {any}
     * @memberof ImageCreatedOut
     */
    readonly isThreesixty?: any;
    /**
     * The signed AWS S3 URL for the image to be uploaded to.
     * @type {any}
     * @memberof ImageCreatedOut
     */
    readonly s3PutObjectUrl?: any;
}


/**
 * @export
 */
export const ImageCreatedOutAiVersionEnum = {
    _11: '1.1',
    _30: '3.0',
    _31: '3.1',
    _32: '3.2',
    _33: '3.3',
    _40: '4.0',
    Null: 'null'
} as const;
export type ImageCreatedOutAiVersionEnum = typeof ImageCreatedOutAiVersionEnum[keyof typeof ImageCreatedOutAiVersionEnum];

/**
 * @export
 */
export const ImageCreatedOutEnhanceTypeEnum = {
    Property: 'property',
    PropertyUsa: 'property_usa',
    Warm: 'warm',
    Neutral: 'neutral',
    Authentic: 'authentic',
    Null: 'null'
} as const;
export type ImageCreatedOutEnhanceTypeEnum = typeof ImageCreatedOutEnhanceTypeEnum[keyof typeof ImageCreatedOutEnhanceTypeEnum];

/**
 * @export
 */
export const ImageCreatedOutContrastBoostEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageCreatedOutContrastBoostEnum = typeof ImageCreatedOutContrastBoostEnum[keyof typeof ImageCreatedOutContrastBoostEnum];

/**
 * @export
 */
export const ImageCreatedOutBrightnessBoostEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageCreatedOutBrightnessBoostEnum = typeof ImageCreatedOutBrightnessBoostEnum[keyof typeof ImageCreatedOutBrightnessBoostEnum];

/**
 * @export
 */
export const ImageCreatedOutSaturationLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageCreatedOutSaturationLevelEnum = typeof ImageCreatedOutSaturationLevelEnum[keyof typeof ImageCreatedOutSaturationLevelEnum];

/**
 * @export
 */
export const ImageCreatedOutSharpenLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageCreatedOutSharpenLevelEnum = typeof ImageCreatedOutSharpenLevelEnum[keyof typeof ImageCreatedOutSharpenLevelEnum];

/**
 * @export
 */
export const ImageCreatedOutDenoiseLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageCreatedOutDenoiseLevelEnum = typeof ImageCreatedOutDenoiseLevelEnum[keyof typeof ImageCreatedOutDenoiseLevelEnum];

/**
 * @export
 */
export const ImageCreatedOutClarityLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageCreatedOutClarityLevelEnum = typeof ImageCreatedOutClarityLevelEnum[keyof typeof ImageCreatedOutClarityLevelEnum];

/**
 * @export
 */
export const ImageCreatedOutCloudTypeEnum = {
    Clear: 'CLEAR',
    LowCloud: 'LOW_CLOUD',
    HighCloud: 'HIGH_CLOUD',
    Null: 'null'
} as const;
export type ImageCreatedOutCloudTypeEnum = typeof ImageCreatedOutCloudTypeEnum[keyof typeof ImageCreatedOutCloudTypeEnum];

/**
 * @export
 */
export const ImageCreatedOutSkySaturationLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageCreatedOutSkySaturationLevelEnum = typeof ImageCreatedOutSkySaturationLevelEnum[keyof typeof ImageCreatedOutSkySaturationLevelEnum];

/**
 * @export
 */
export const ImageCreatedOutContrastBoostInternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageCreatedOutContrastBoostInternalEnum = typeof ImageCreatedOutContrastBoostInternalEnum[keyof typeof ImageCreatedOutContrastBoostInternalEnum];

/**
 * @export
 */
export const ImageCreatedOutContrastBoostExternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageCreatedOutContrastBoostExternalEnum = typeof ImageCreatedOutContrastBoostExternalEnum[keyof typeof ImageCreatedOutContrastBoostExternalEnum];

/**
 * @export
 */
export const ImageCreatedOutBrightnessBoostInternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageCreatedOutBrightnessBoostInternalEnum = typeof ImageCreatedOutBrightnessBoostInternalEnum[keyof typeof ImageCreatedOutBrightnessBoostInternalEnum];

/**
 * @export
 */
export const ImageCreatedOutBrightnessBoostExternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageCreatedOutBrightnessBoostExternalEnum = typeof ImageCreatedOutBrightnessBoostExternalEnum[keyof typeof ImageCreatedOutBrightnessBoostExternalEnum];

/**
 * @export
 */
export const ImageCreatedOutStatusEnum = {
    Waiting: 'waiting',
    Processing: 'processing',
    Processed: 'processed',
    Error: 'error'
} as const;
export type ImageCreatedOutStatusEnum = typeof ImageCreatedOutStatusEnum[keyof typeof ImageCreatedOutStatusEnum];


/**
 * Check if a given object implements the ImageCreatedOut interface.
 */
export function instanceOfImageCreatedOut(value: object): boolean {
    return true;
}

export function ImageCreatedOutFromJSON(json: any): ImageCreatedOut {
    return ImageCreatedOutFromJSONTyped(json, false);
}

export function ImageCreatedOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageCreatedOut {
    if (json == null) {
        return json;
    }
    return {
        
        'aiVersion': json['ai_version'] == null ? undefined : json['ai_version'],
        'enhanceType': json['enhance_type'] == null ? undefined : json['enhance_type'],
        'skyReplacement': json['sky_replacement'] == null ? undefined : json['sky_replacement'],
        'verticalCorrection': json['vertical_correction'] == null ? undefined : json['vertical_correction'],
        'lensCorrection': json['lens_correction'] == null ? undefined : json['lens_correction'],
        'contrastBoost': json['contrast_boost'] == null ? undefined : json['contrast_boost'],
        'brightnessBoost': json['brightness_boost'] == null ? undefined : json['brightness_boost'],
        'saturationLevel': json['saturation_level'] == null ? undefined : json['saturation_level'],
        'sharpenLevel': json['sharpen_level'] == null ? undefined : json['sharpen_level'],
        'denoiseLevel': json['denoise_level'] == null ? undefined : json['denoise_level'],
        'clarityLevel': json['clarity_level'] == null ? undefined : json['clarity_level'],
        'privacy': json['privacy'] == null ? undefined : json['privacy'],
        'windowPull': json['window_pull'] == null ? undefined : json['window_pull'],
        'cloudType': json['cloud_type'] == null ? undefined : json['cloud_type'],
        'skySaturationLevel': json['sky_saturation_level'] == null ? undefined : json['sky_saturation_level'],
        'contrastBoostInternal': json['contrast_boost_internal'] == null ? undefined : json['contrast_boost_internal'],
        'contrastBoostExternal': json['contrast_boost_external'] == null ? undefined : json['contrast_boost_external'],
        'brightnessBoostInternal': json['brightness_boost_internal'] == null ? undefined : json['brightness_boost_internal'],
        'brightnessBoostExternal': json['brightness_boost_external'] == null ? undefined : json['brightness_boost_external'],
        'imageId': json['image_id'] == null ? undefined : json['image_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'imageName': json['image_name'] == null ? undefined : json['image_name'],
        'imageType': json['image_type'] == null ? undefined : json['image_type'],
        'dateAdded': json['date_added'] == null ? undefined : json['date_added'],
        'scene': json['scene'] == null ? undefined : json['scene'],
        'status': json['status'] == null ? undefined : json['status'],
        'enhanced': json['enhanced'] == null ? undefined : json['enhanced'],
        'error': json['error'] == null ? undefined : json['error'],
        'downloaded': json['downloaded'] == null ? undefined : json['downloaded'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'isThreesixty': json['is_threesixty'] == null ? undefined : json['is_threesixty'],
        's3PutObjectUrl': json['s3PutObjectUrl'] == null ? undefined : json['s3PutObjectUrl'],
    };
}

export function ImageCreatedOutToJSON(value?: ImageCreatedOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ai_version': value['aiVersion'],
        'enhance_type': value['enhanceType'],
        'sky_replacement': value['skyReplacement'],
        'vertical_correction': value['verticalCorrection'],
        'lens_correction': value['lensCorrection'],
        'contrast_boost': value['contrastBoost'],
        'brightness_boost': value['brightnessBoost'],
        'saturation_level': value['saturationLevel'],
        'sharpen_level': value['sharpenLevel'],
        'denoise_level': value['denoiseLevel'],
        'clarity_level': value['clarityLevel'],
        'privacy': value['privacy'],
        'window_pull': value['windowPull'],
        'cloud_type': value['cloudType'],
        'sky_saturation_level': value['skySaturationLevel'],
        'contrast_boost_internal': value['contrastBoostInternal'],
        'contrast_boost_external': value['contrastBoostExternal'],
        'brightness_boost_internal': value['brightnessBoostInternal'],
        'brightness_boost_external': value['brightnessBoostExternal'],
        'image_id': value['imageId'],
        'user_id': value['userId'],
        'order_id': value['orderId'],
        'image_name': value['imageName'],
        'image_type': value['imageType'],
        'date_added': value['dateAdded'],
        'scene': value['scene'],
        'enhanced': value['enhanced'],
        'error': value['error'],
        'downloaded': value['downloaded'],
        'rating': value['rating'],
    };
}

