/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageIn
 */
export interface ImageIn {
    /**
     * A rating between 0 and 5 on how good the image enhancmeent. Higher is better.
     * @type {number}
     * @memberof ImageIn
     */
    rating?: number;
    /**
     * The version of the AI to use.
     * @type {number}
     * @memberof ImageIn
     */
    aiVersion?: ImageInAiVersionEnum;
    /**
     * Enable the replacement of the original sky for a summer sky.
     * @type {boolean}
     * @memberof ImageIn
     */
    skyReplacement?: boolean;
    /**
     * Correct any vertical distortion in the image so that it appears straight.
     * @type {boolean}
     * @memberof ImageIn
     */
    verticalCorrection?: boolean;
    /**
     * Correct any lens distortion in the image.
     * @type {boolean}
     * @memberof ImageIn
     */
    lensCorrection?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ImageIn
     */
    vibrant?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ImageIn
     */
    enhanceType?: ImageInEnhanceTypeEnum;
    /**
     * The amount of contrast boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageIn
     */
    contrastBoost?: ImageInContrastBoostEnum;
    /**
     * The amount of brightness boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageIn
     */
    brightnessBoost?: ImageInBrightnessBoostEnum;
    /**
     * The amount of saturation to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageIn
     */
    saturationLevel?: ImageInSaturationLevelEnum;
    /**
     * The amount of sharpening to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageIn
     */
    sharpenLevel?: ImageInSharpenLevelEnum;
    /**
     * The amount of denoising to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageIn
     */
    denoiseLevel?: ImageInDenoiseLevelEnum;
    /**
     * The amount of clarity to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageIn
     */
    clarityLevel?: ImageInClarityLevelEnum;
    /**
     * Whether to blur any faces or license plates in the image.
     * @type {boolean}
     * @memberof ImageIn
     */
    privacy?: boolean;
    /**
     * The type of sky to replace the original sky with. Options include: UK_SUMMER, UK_WINTER, USA_SUMMER
     * @type {string}
     * @memberof ImageIn
     */
    skyType?: ImageInSkyTypeEnum;
    /**
     * The type of clouds in the new sky to replace the original sky with. Options include: CLEAR, LOW_CLOUD, LOW_CLOUD_LOW_SAT, HIGH_CLOUD, EHOUSE
     * @type {string}
     * @memberof ImageIn
     */
    cloudType?: ImageInCloudTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageIn
     */
    contrastBoostInternal?: ImageInContrastBoostInternalEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageIn
     */
    contrastBoostExternal?: ImageInContrastBoostExternalEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageIn
     */
    brightnessBoostInternal?: ImageInBrightnessBoostInternalEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageIn
     */
    brightnessBoostExternal?: ImageInBrightnessBoostExternalEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageIn
     */
    saturationBoostLevel?: ImageInSaturationBoostLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageIn
     */
    skySaturationLevel?: ImageInSkySaturationLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageIn
     */
    imageName: string;
    /**
     * 
     * @type {string}
     * @memberof ImageIn
     */
    orderId?: string;
    /**
     * The MIME type of the image i.e. image/jpeg, image/png, etc.
     * @type {string}
     * @memberof ImageIn
     */
    contentType?: string;
    /**
     * Whether the image is a 360 image.
     * @type {boolean}
     * @memberof ImageIn
     */
    threesixty?: boolean;
    /**
     * Whether the image is a HDR bracket. An order_id must be provided when this is set to true.
     * @type {boolean}
     * @memberof ImageIn
     */
    hdr?: boolean;
}


/**
 * @export
 */
export const ImageInAiVersionEnum = {
    NUMBER_1_DOT_0: 1.0,
    NUMBER_1_DOT_1: 1.1,
    NUMBER_3_DOT_0: 3.0,
    NUMBER_3_DOT_1: 3.1,
    NUMBER_4_DOT_0: 4.0
} as const;
export type ImageInAiVersionEnum = typeof ImageInAiVersionEnum[keyof typeof ImageInAiVersionEnum];

/**
 * @export
 */
export const ImageInEnhanceTypeEnum = {
    Property: 'property',
    PropertyUsa: 'property_usa'
} as const;
export type ImageInEnhanceTypeEnum = typeof ImageInEnhanceTypeEnum[keyof typeof ImageInEnhanceTypeEnum];

/**
 * @export
 */
export const ImageInContrastBoostEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type ImageInContrastBoostEnum = typeof ImageInContrastBoostEnum[keyof typeof ImageInContrastBoostEnum];

/**
 * @export
 */
export const ImageInBrightnessBoostEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type ImageInBrightnessBoostEnum = typeof ImageInBrightnessBoostEnum[keyof typeof ImageInBrightnessBoostEnum];

/**
 * @export
 */
export const ImageInSaturationLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type ImageInSaturationLevelEnum = typeof ImageInSaturationLevelEnum[keyof typeof ImageInSaturationLevelEnum];

/**
 * @export
 */
export const ImageInSharpenLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type ImageInSharpenLevelEnum = typeof ImageInSharpenLevelEnum[keyof typeof ImageInSharpenLevelEnum];

/**
 * @export
 */
export const ImageInDenoiseLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type ImageInDenoiseLevelEnum = typeof ImageInDenoiseLevelEnum[keyof typeof ImageInDenoiseLevelEnum];

/**
 * @export
 */
export const ImageInClarityLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type ImageInClarityLevelEnum = typeof ImageInClarityLevelEnum[keyof typeof ImageInClarityLevelEnum];

/**
 * @export
 */
export const ImageInSkyTypeEnum = {
    UkSummer: 'UK_SUMMER',
    UkWinter: 'UK_WINTER',
    UsaSummer: 'USA_SUMMER'
} as const;
export type ImageInSkyTypeEnum = typeof ImageInSkyTypeEnum[keyof typeof ImageInSkyTypeEnum];

/**
 * @export
 */
export const ImageInCloudTypeEnum = {
    Clear: 'CLEAR',
    LowCloud: 'LOW_CLOUD',
    LowCloudLowSat: 'LOW_CLOUD_LOW_SAT',
    HighCloud: 'HIGH_CLOUD',
    Ehouse: 'EHOUSE'
} as const;
export type ImageInCloudTypeEnum = typeof ImageInCloudTypeEnum[keyof typeof ImageInCloudTypeEnum];

/**
 * @export
 */
export const ImageInContrastBoostInternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type ImageInContrastBoostInternalEnum = typeof ImageInContrastBoostInternalEnum[keyof typeof ImageInContrastBoostInternalEnum];

/**
 * @export
 */
export const ImageInContrastBoostExternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type ImageInContrastBoostExternalEnum = typeof ImageInContrastBoostExternalEnum[keyof typeof ImageInContrastBoostExternalEnum];

/**
 * @export
 */
export const ImageInBrightnessBoostInternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type ImageInBrightnessBoostInternalEnum = typeof ImageInBrightnessBoostInternalEnum[keyof typeof ImageInBrightnessBoostInternalEnum];

/**
 * @export
 */
export const ImageInBrightnessBoostExternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type ImageInBrightnessBoostExternalEnum = typeof ImageInBrightnessBoostExternalEnum[keyof typeof ImageInBrightnessBoostExternalEnum];

/**
 * @export
 */
export const ImageInSaturationBoostLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type ImageInSaturationBoostLevelEnum = typeof ImageInSaturationBoostLevelEnum[keyof typeof ImageInSaturationBoostLevelEnum];

/**
 * @export
 */
export const ImageInSkySaturationLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type ImageInSkySaturationLevelEnum = typeof ImageInSkySaturationLevelEnum[keyof typeof ImageInSkySaturationLevelEnum];


/**
 * Check if a given object implements the ImageIn interface.
 */
export function instanceOfImageIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "imageName" in value;

    return isInstance;
}

export function ImageInFromJSON(json: any): ImageIn {
    return ImageInFromJSONTyped(json, false);
}

export function ImageInFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'aiVersion': !exists(json, 'ai_version') ? undefined : json['ai_version'],
        'skyReplacement': !exists(json, 'sky_replacement') ? undefined : json['sky_replacement'],
        'verticalCorrection': !exists(json, 'vertical_correction') ? undefined : json['vertical_correction'],
        'lensCorrection': !exists(json, 'lens_correction') ? undefined : json['lens_correction'],
        'vibrant': !exists(json, 'vibrant') ? undefined : json['vibrant'],
        'enhanceType': !exists(json, 'enhance_type') ? undefined : json['enhance_type'],
        'contrastBoost': !exists(json, 'contrast_boost') ? undefined : json['contrast_boost'],
        'brightnessBoost': !exists(json, 'brightness_boost') ? undefined : json['brightness_boost'],
        'saturationLevel': !exists(json, 'saturation_level') ? undefined : json['saturation_level'],
        'sharpenLevel': !exists(json, 'sharpen_level') ? undefined : json['sharpen_level'],
        'denoiseLevel': !exists(json, 'denoise_level') ? undefined : json['denoise_level'],
        'clarityLevel': !exists(json, 'clarity_level') ? undefined : json['clarity_level'],
        'privacy': !exists(json, 'privacy') ? undefined : json['privacy'],
        'skyType': !exists(json, 'sky_type') ? undefined : json['sky_type'],
        'cloudType': !exists(json, 'cloud_type') ? undefined : json['cloud_type'],
        'contrastBoostInternal': !exists(json, 'contrast_boost_internal') ? undefined : json['contrast_boost_internal'],
        'contrastBoostExternal': !exists(json, 'contrast_boost_external') ? undefined : json['contrast_boost_external'],
        'brightnessBoostInternal': !exists(json, 'brightness_boost_internal') ? undefined : json['brightness_boost_internal'],
        'brightnessBoostExternal': !exists(json, 'brightness_boost_external') ? undefined : json['brightness_boost_external'],
        'saturationBoostLevel': !exists(json, 'saturation_boost_level') ? undefined : json['saturation_boost_level'],
        'skySaturationLevel': !exists(json, 'sky_saturation_level') ? undefined : json['sky_saturation_level'],
        'imageName': json['image_name'],
        'orderId': !exists(json, 'order_id') ? undefined : json['order_id'],
        'contentType': !exists(json, 'content_type') ? undefined : json['content_type'],
        'threesixty': !exists(json, 'threesixty') ? undefined : json['threesixty'],
        'hdr': !exists(json, 'hdr') ? undefined : json['hdr'],
    };
}

export function ImageInToJSON(value?: ImageIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rating': value.rating,
        'ai_version': value.aiVersion,
        'sky_replacement': value.skyReplacement,
        'vertical_correction': value.verticalCorrection,
        'lens_correction': value.lensCorrection,
        'vibrant': value.vibrant,
        'enhance_type': value.enhanceType,
        'contrast_boost': value.contrastBoost,
        'brightness_boost': value.brightnessBoost,
        'saturation_level': value.saturationLevel,
        'sharpen_level': value.sharpenLevel,
        'denoise_level': value.denoiseLevel,
        'clarity_level': value.clarityLevel,
        'privacy': value.privacy,
        'sky_type': value.skyType,
        'cloud_type': value.cloudType,
        'contrast_boost_internal': value.contrastBoostInternal,
        'contrast_boost_external': value.contrastBoostExternal,
        'brightness_boost_internal': value.brightnessBoostInternal,
        'brightness_boost_external': value.brightnessBoostExternal,
        'saturation_boost_level': value.saturationBoostLevel,
        'sky_saturation_level': value.skySaturationLevel,
        'image_name': value.imageName,
        'order_id': value.orderId,
        'content_type': value.contentType,
        'threesixty': value.threesixty,
        'hdr': value.hdr,
    };
}

