/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageInUpdate
 */
export interface ImageInUpdate {
    /**
     * The version of the AI model to use for enhancing the image. Versions ending in an .x will use the latest minor version as soon as it's published.
     * @type {string}
     * @memberof ImageInUpdate
     */
    aiVersion?: string;
    /**
     * The amount of brightness boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageInUpdate
     */
    brightnessBoost?: ImageInUpdateBrightnessBoostEnum | null;
    /**
     * The amount of external brightness boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageInUpdate
     */
    brightnessBoostExternal?: ImageInUpdateBrightnessBoostExternalEnum | null;
    /**
     * The amount of external brightness boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageInUpdate
     */
    brightnessBoostInternal?: ImageInUpdateBrightnessBoostInternalEnum | null;
    /**
     * The amount of clarity to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageInUpdate
     */
    clarityLevel?: ImageInUpdateClarityLevelEnum | null;
    /**
     * The type of clouds in the new sky to replace the original sky with. Options include: CLEAR, LOW_CLOUD, HIGH_CLOUD
     * @type {string}
     * @memberof ImageInUpdate
     */
    cloudType?: ImageInUpdateCloudTypeEnum | null;
    /**
     * The MIME type of the image i.e. image/jpeg, image/png, etc.
     * @type {string}
     * @memberof ImageInUpdate
     */
    contentType?: string;
    /**
     * The amount of contrast boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageInUpdate
     */
    contrastBoost?: ImageInUpdateContrastBoostEnum | null;
    /**
     * The amount of external contrast boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageInUpdate
     */
    contrastBoostExternal?: ImageInUpdateContrastBoostExternalEnum | null;
    /**
     * The amount of internal contrast boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageInUpdate
     */
    contrastBoostInternal?: ImageInUpdateContrastBoostInternalEnum | null;
    /**
     * The amount of denoising to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageInUpdate
     */
    denoiseLevel?: ImageInUpdateDenoiseLevelEnum | null;
    /**
     * Whether to enhance the image.
     * @type {boolean}
     * @memberof ImageInUpdate
     */
    enhance?: boolean;
    /**
     * The type of enhancement to apply to the image. PROPERTY or PROPERTY_USA is used with AI version < 4.0, for >= 4.0 use WARM, NEUTRAL, or AUTHENTIC.
     * @type {string}
     * @memberof ImageInUpdate
     */
    enhanceType?: ImageInUpdateEnhanceTypeEnum;
    /**
     * Whether the image is a HDR bracket. An order_id must be provided when this is set to true.
     * @type {boolean}
     * @memberof ImageInUpdate
     */
    hdr?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ImageInUpdate
     */
    imageName?: string;
    /**
     * Correct any lens distortion in the image.
     * @type {boolean}
     * @memberof ImageInUpdate
     */
    lensCorrection?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ImageInUpdate
     */
    orderId?: string;
    /**
     * Whether to blur any faces or license plates in the image.
     * @type {boolean}
     * @memberof ImageInUpdate
     */
    privacy?: boolean | null;
    /**
     * A rating between 0 and 5 on how good the image enhancmeent. Higher is better.
     * @type {number}
     * @memberof ImageInUpdate
     */
    rating?: number;
    /**
     * The amount of saturation to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageInUpdate
     */
    saturationLevel?: ImageInUpdateSaturationLevelEnum | null;
    /**
     * The amount of sharpening to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof ImageInUpdate
     */
    sharpenLevel?: ImageInUpdateSharpenLevelEnum | null;
    /**
     * Enable the replacement of the original sky for a summer sky.
     * @type {boolean}
     * @memberof ImageInUpdate
     */
    skyReplacement?: boolean;
    /**
     * Whether the image is a 360 image.
     * @type {boolean}
     * @memberof ImageInUpdate
     */
    threesixty?: boolean;
    /**
     * Correct any vertical distortion in the image so that it appears straight.
     * @type {boolean}
     * @memberof ImageInUpdate
     */
    verticalCorrection?: boolean;
    /**
     * Whether to pull the windows in the image (used with AI version >= 4.0).
     * @type {boolean}
     * @memberof ImageInUpdate
     */
    windowPull?: boolean | null;
}


/**
 * @export
 */
export const ImageInUpdateBrightnessBoostEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageInUpdateBrightnessBoostEnum = typeof ImageInUpdateBrightnessBoostEnum[keyof typeof ImageInUpdateBrightnessBoostEnum];

/**
 * @export
 */
export const ImageInUpdateBrightnessBoostExternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageInUpdateBrightnessBoostExternalEnum = typeof ImageInUpdateBrightnessBoostExternalEnum[keyof typeof ImageInUpdateBrightnessBoostExternalEnum];

/**
 * @export
 */
export const ImageInUpdateBrightnessBoostInternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageInUpdateBrightnessBoostInternalEnum = typeof ImageInUpdateBrightnessBoostInternalEnum[keyof typeof ImageInUpdateBrightnessBoostInternalEnum];

/**
 * @export
 */
export const ImageInUpdateClarityLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageInUpdateClarityLevelEnum = typeof ImageInUpdateClarityLevelEnum[keyof typeof ImageInUpdateClarityLevelEnum];

/**
 * @export
 */
export const ImageInUpdateCloudTypeEnum = {
    Clear: 'CLEAR',
    LowCloud: 'LOW_CLOUD',
    HighCloud: 'HIGH_CLOUD',
    Null: 'null'
} as const;
export type ImageInUpdateCloudTypeEnum = typeof ImageInUpdateCloudTypeEnum[keyof typeof ImageInUpdateCloudTypeEnum];

/**
 * @export
 */
export const ImageInUpdateContrastBoostEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageInUpdateContrastBoostEnum = typeof ImageInUpdateContrastBoostEnum[keyof typeof ImageInUpdateContrastBoostEnum];

/**
 * @export
 */
export const ImageInUpdateContrastBoostExternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageInUpdateContrastBoostExternalEnum = typeof ImageInUpdateContrastBoostExternalEnum[keyof typeof ImageInUpdateContrastBoostExternalEnum];

/**
 * @export
 */
export const ImageInUpdateContrastBoostInternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageInUpdateContrastBoostInternalEnum = typeof ImageInUpdateContrastBoostInternalEnum[keyof typeof ImageInUpdateContrastBoostInternalEnum];

/**
 * @export
 */
export const ImageInUpdateDenoiseLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageInUpdateDenoiseLevelEnum = typeof ImageInUpdateDenoiseLevelEnum[keyof typeof ImageInUpdateDenoiseLevelEnum];

/**
 * @export
 */
export const ImageInUpdateEnhanceTypeEnum = {
    Property: 'property',
    PropertyUsa: 'property_usa',
    Warm: 'warm',
    Neutral: 'neutral',
    Authentic: 'authentic'
} as const;
export type ImageInUpdateEnhanceTypeEnum = typeof ImageInUpdateEnhanceTypeEnum[keyof typeof ImageInUpdateEnhanceTypeEnum];

/**
 * @export
 */
export const ImageInUpdateSaturationLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageInUpdateSaturationLevelEnum = typeof ImageInUpdateSaturationLevelEnum[keyof typeof ImageInUpdateSaturationLevelEnum];

/**
 * @export
 */
export const ImageInUpdateSharpenLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type ImageInUpdateSharpenLevelEnum = typeof ImageInUpdateSharpenLevelEnum[keyof typeof ImageInUpdateSharpenLevelEnum];


/**
 * Check if a given object implements the ImageInUpdate interface.
 */
export function instanceOfImageInUpdate(value: object): value is ImageInUpdate {
    return true;
}

export function ImageInUpdateFromJSON(json: any): ImageInUpdate {
    return ImageInUpdateFromJSONTyped(json, false);
}

export function ImageInUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageInUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'aiVersion': json['ai_version'] == null ? undefined : json['ai_version'],
        'brightnessBoost': json['brightness_boost'] == null ? undefined : json['brightness_boost'],
        'brightnessBoostExternal': json['brightness_boost_external'] == null ? undefined : json['brightness_boost_external'],
        'brightnessBoostInternal': json['brightness_boost_internal'] == null ? undefined : json['brightness_boost_internal'],
        'clarityLevel': json['clarity_level'] == null ? undefined : json['clarity_level'],
        'cloudType': json['cloud_type'] == null ? undefined : json['cloud_type'],
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
        'contrastBoost': json['contrast_boost'] == null ? undefined : json['contrast_boost'],
        'contrastBoostExternal': json['contrast_boost_external'] == null ? undefined : json['contrast_boost_external'],
        'contrastBoostInternal': json['contrast_boost_internal'] == null ? undefined : json['contrast_boost_internal'],
        'denoiseLevel': json['denoise_level'] == null ? undefined : json['denoise_level'],
        'enhance': json['enhance'] == null ? undefined : json['enhance'],
        'enhanceType': json['enhance_type'] == null ? undefined : json['enhance_type'],
        'hdr': json['hdr'] == null ? undefined : json['hdr'],
        'imageName': json['image_name'] == null ? undefined : json['image_name'],
        'lensCorrection': json['lens_correction'] == null ? undefined : json['lens_correction'],
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'privacy': json['privacy'] == null ? undefined : json['privacy'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'saturationLevel': json['saturation_level'] == null ? undefined : json['saturation_level'],
        'sharpenLevel': json['sharpen_level'] == null ? undefined : json['sharpen_level'],
        'skyReplacement': json['sky_replacement'] == null ? undefined : json['sky_replacement'],
        'threesixty': json['threesixty'] == null ? undefined : json['threesixty'],
        'verticalCorrection': json['vertical_correction'] == null ? undefined : json['vertical_correction'],
        'windowPull': json['window_pull'] == null ? undefined : json['window_pull'],
    };
}

export function ImageInUpdateToJSON(value?: ImageInUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ai_version': value['aiVersion'],
        'brightness_boost': value['brightnessBoost'],
        'brightness_boost_external': value['brightnessBoostExternal'],
        'brightness_boost_internal': value['brightnessBoostInternal'],
        'clarity_level': value['clarityLevel'],
        'cloud_type': value['cloudType'],
        'content_type': value['contentType'],
        'contrast_boost': value['contrastBoost'],
        'contrast_boost_external': value['contrastBoostExternal'],
        'contrast_boost_internal': value['contrastBoostInternal'],
        'denoise_level': value['denoiseLevel'],
        'enhance': value['enhance'],
        'enhance_type': value['enhanceType'],
        'hdr': value['hdr'],
        'image_name': value['imageName'],
        'lens_correction': value['lensCorrection'],
        'order_id': value['orderId'],
        'privacy': value['privacy'],
        'rating': value['rating'],
        'saturation_level': value['saturationLevel'],
        'sharpen_level': value['sharpenLevel'],
        'sky_replacement': value['skyReplacement'],
        'threesixty': value['threesixty'],
        'vertical_correction': value['verticalCorrection'],
        'window_pull': value['windowPull'],
    };
}

