/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageCreatedOut
 */
export interface ImageCreatedOut {
    /**
     * 
     * @type {string}
     * @memberof ImageCreatedOut
     */
    imageId?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageCreatedOut
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageCreatedOut
     */
    imageType?: string;
    /**
     * 
     * @type {any}
     * @memberof ImageCreatedOut
     */
    readonly s3PutObjectUrl?: any | null;
}

/**
 * Check if a given object implements the ImageCreatedOut interface.
 */
export function instanceOfImageCreatedOut(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ImageCreatedOutFromJSON(json: any): ImageCreatedOut {
    return ImageCreatedOutFromJSONTyped(json, false);
}

export function ImageCreatedOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageCreatedOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageId': !exists(json, 'image_id') ? undefined : json['image_id'],
        'orderId': !exists(json, 'order_id') ? undefined : json['order_id'],
        'imageType': !exists(json, 'image_type') ? undefined : json['image_type'],
        's3PutObjectUrl': !exists(json, 's3PutObjectUrl') ? undefined : json['s3PutObjectUrl'],
    };
}

export function ImageCreatedOutToJSON(value?: ImageCreatedOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image_id': value.imageId,
        'order_id': value.orderId,
        'image_type': value.imageType,
    };
}

