/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageOut
 */
export interface ImageOut {
    /**
     * The version of the AI model to use for enhancing the image. Versions ending in an .x will use the latest minor version as soon as it's published.
     * @type {string}
     * @memberof ImageOut
     */
    aiVersion?: ImageOutAiVersionEnum;
    /**
     * The type of clouds in the new sky to replace the original sky with. Options include: CLEAR, LOW_CLOUD, HIGH_CLOUD
     * @type {string}
     * @memberof ImageOut
     */
    cloudType?: ImageOutCloudTypeEnum | null;
    /**
     * The date the image was registered with Autoenhance.
     * @type {number}
     * @memberof ImageOut
     */
    dateAdded?: number;
    /**
     * Whether image has been already downloaded and paid for.
     * @type {boolean}
     * @memberof ImageOut
     */
    downloaded?: boolean;
    /**
     * Whether to enhance the image.
     * @type {boolean}
     * @memberof ImageOut
     */
    enhance?: boolean;
    /**
     * The type of enhancement to apply to the image. PROPERTY or PROPERTY_USA is used with AI version < 4.0, for >= 4.0 use WARM or NEUTRAL..
     * @type {string}
     * @memberof ImageOut
     */
    enhanceType?: ImageOutEnhanceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageOut
     */
    imageId?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageOut
     */
    imageName?: string;
    /**
     * The image type for the image.
     * @type {string}
     * @memberof ImageOut
     */
    imageType?: string;
    /**
     * Whether the image is a 360° image
     * @type {any}
     * @memberof ImageOut
     */
    readonly isThreesixty?: any | null;
    /**
     * Correct any lens distortion in the image.
     * @type {boolean}
     * @memberof ImageOut
     */
    lensCorrection?: boolean;
    /**
     * Metadata for the image.
     * @type {{ [key: string]: any; }}
     * @memberof ImageOut
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {any}
     * @memberof ImageOut
     */
    readonly orderId?: any | null;
    /**
     * Whether to blur any faces or license plates in the image.
     * @type {boolean}
     * @memberof ImageOut
     */
    privacy?: boolean | null;
    /**
     * A rating between 0 and 5 on how good the image enhancmeent. Higher is better.
     * @type {number}
     * @memberof ImageOut
     */
    rating?: number;
    /**
     * The detected scene of the image i.e garden, patio, kitchen, etc.
     * @type {string}
     * @memberof ImageOut
     */
    scene?: string;
    /**
     * Whether the sky replacement feature was enabled for the image.
     * @type {boolean}
     * @memberof ImageOut
     */
    skyReplacement?: boolean;
    /**
     * The status of the order.
     * @type {any}
     * @memberof ImageOut
     */
    readonly status?: any | null;
    /**
     * Reason for the image's current status
     * @type {any}
     * @memberof ImageOut
     */
    readonly statusReason?: any | null;
    /**
     * Whether to upscale the image.
     * @type {boolean}
     * @memberof ImageOut
     */
    upscale?: boolean;
    /**
     * The user ID of the user who uploaded (owns) the image.
     * @type {any}
     * @memberof ImageOut
     */
    readonly userId?: any | null;
    /**
     * Whether the vertical correction feature was enabled for the image.
     * @type {boolean}
     * @memberof ImageOut
     */
    verticalCorrection?: boolean;
    /**
     * Whether to pull the windows in the image (used with AI version >= 4.0).
     * @type {boolean}
     * @memberof ImageOut
     */
    windowPull?: boolean | null;
}


/**
 * @export
 */
export const ImageOutAiVersionEnum = {
    Dev: 'dev',
    _4X: '4.x',
    _47: '4.7',
    _45: '4.5',
    _44: '4.4',
    _43: '4.3',
    _42: '4.2',
    _41: '4.1',
    _40: '4.0',
    _3X: '3.x',
    _35: '3.5',
    _34: '3.4',
    _33: '3.3',
    _32: '3.2',
    _31: '3.1',
    _30: '3.0'
} as const;
export type ImageOutAiVersionEnum = typeof ImageOutAiVersionEnum[keyof typeof ImageOutAiVersionEnum];

/**
 * @export
 */
export const ImageOutCloudTypeEnum = {
    Clear: 'CLEAR',
    LowCloud: 'LOW_CLOUD',
    HighCloud: 'HIGH_CLOUD'
} as const;
export type ImageOutCloudTypeEnum = typeof ImageOutCloudTypeEnum[keyof typeof ImageOutCloudTypeEnum];

/**
 * @export
 */
export const ImageOutEnhanceTypeEnum = {
    Property: 'property',
    PropertyUsa: 'property_usa',
    Warm: 'warm',
    Neutral: 'neutral'
} as const;
export type ImageOutEnhanceTypeEnum = typeof ImageOutEnhanceTypeEnum[keyof typeof ImageOutEnhanceTypeEnum];


/**
 * Check if a given object implements the ImageOut interface.
 */
export function instanceOfImageOut(value: object): value is ImageOut {
    return true;
}

export function ImageOutFromJSON(json: any): ImageOut {
    return ImageOutFromJSONTyped(json, false);
}

export function ImageOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageOut {
    if (json == null) {
        return json;
    }
    return {
        
        'aiVersion': json['ai_version'] == null ? undefined : json['ai_version'],
        'cloudType': json['cloud_type'] == null ? undefined : json['cloud_type'],
        'dateAdded': json['date_added'] == null ? undefined : json['date_added'],
        'downloaded': json['downloaded'] == null ? undefined : json['downloaded'],
        'enhance': json['enhance'] == null ? undefined : json['enhance'],
        'enhanceType': json['enhance_type'] == null ? undefined : json['enhance_type'],
        'imageId': json['image_id'] == null ? undefined : json['image_id'],
        'imageName': json['image_name'] == null ? undefined : json['image_name'],
        'imageType': json['image_type'] == null ? undefined : json['image_type'],
        'isThreesixty': json['is_threesixty'] == null ? undefined : json['is_threesixty'],
        'lensCorrection': json['lens_correction'] == null ? undefined : json['lens_correction'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'privacy': json['privacy'] == null ? undefined : json['privacy'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'scene': json['scene'] == null ? undefined : json['scene'],
        'skyReplacement': json['sky_replacement'] == null ? undefined : json['sky_replacement'],
        'status': json['status'] == null ? undefined : json['status'],
        'statusReason': json['status_reason'] == null ? undefined : json['status_reason'],
        'upscale': json['upscale'] == null ? undefined : json['upscale'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'verticalCorrection': json['vertical_correction'] == null ? undefined : json['vertical_correction'],
        'windowPull': json['window_pull'] == null ? undefined : json['window_pull'],
    };
}

export function ImageOutToJSON(json: any): ImageOut {
    return ImageOutToJSONTyped(json, false);
}

export function ImageOutToJSONTyped(value?: Omit<ImageOut, 'is_threesixty'|'order_id'|'status'|'status_reason'|'user_id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ai_version': value['aiVersion'],
        'cloud_type': value['cloudType'],
        'date_added': value['dateAdded'],
        'downloaded': value['downloaded'],
        'enhance': value['enhance'],
        'enhance_type': value['enhanceType'],
        'image_id': value['imageId'],
        'image_name': value['imageName'],
        'image_type': value['imageType'],
        'lens_correction': value['lensCorrection'],
        'metadata': value['metadata'],
        'privacy': value['privacy'],
        'rating': value['rating'],
        'scene': value['scene'],
        'sky_replacement': value['skyReplacement'],
        'upscale': value['upscale'],
        'vertical_correction': value['verticalCorrection'],
        'window_pull': value['windowPull'],
    };
}

