/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageOut } from './ImageOut';
import {
    ImageOutFromJSON,
    ImageOutFromJSONTyped,
    ImageOutToJSON,
} from './ImageOut';

/**
 * 
 * @export
 * @interface OrderOut
 */
export interface OrderOut {
    /**
     * The ID for the order.
     * @type {string}
     * @memberof OrderOut
     */
    orderId?: string;
    /**
     * The name for the order.
     * @type {string}
     * @memberof OrderOut
     */
    name?: string;
    /**
     * The creation date of the order.
     * @type {Date}
     * @memberof OrderOut
     */
    createdAt?: Date;
    /**
     * The last updated date of the order.
     * @type {Date}
     * @memberof OrderOut
     */
    lastUpdatedAt?: Date;
    /**
     * 
     * @type {Array<ImageOut>}
     * @memberof OrderOut
     */
    images?: Array<ImageOut>;
    /**
     * The status of the order.
     * @type {string}
     * @memberof OrderOut
     */
    readonly status?: OrderOutStatusEnum;
    /**
     * The processing status for the order
     * @type {any}
     * @memberof OrderOut
     */
    readonly isProcessing?: any;
    /**
     * The processing status for the order
     * @type {boolean}
     * @memberof OrderOut
     */
    isMerging?: boolean;
}


/**
 * @export
 */
export const OrderOutStatusEnum = {
    Waiting: 'waiting',
    Processing: 'processing',
    Processed: 'processed',
    Error: 'error'
} as const;
export type OrderOutStatusEnum = typeof OrderOutStatusEnum[keyof typeof OrderOutStatusEnum];


/**
 * Check if a given object implements the OrderOut interface.
 */
export function instanceOfOrderOut(value: object): value is OrderOut {
    return true;
}

export function OrderOutFromJSON(json: any): OrderOut {
    return OrderOutFromJSONTyped(json, false);
}

export function OrderOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderOut {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'lastUpdatedAt': json['last_updated_at'] == null ? undefined : (new Date(json['last_updated_at'])),
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ImageOutFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
        'isProcessing': json['is_processing'] == null ? undefined : json['is_processing'],
        'isMerging': json['is_merging'] == null ? undefined : json['is_merging'],
    };
}

export function OrderOutToJSON(value?: Omit<OrderOut, 'status'|'is_processing'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'order_id': value['orderId'],
        'name': value['name'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'last_updated_at': value['lastUpdatedAt'] == null ? undefined : ((value['lastUpdatedAt']).toISOString()),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ImageOutToJSON)),
        'is_merging': value['isMerging'],
    };
}

