/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BracketOut } from './BracketOut';
import {
    BracketOutFromJSON,
    BracketOutFromJSONTyped,
    BracketOutToJSON,
} from './BracketOut';

/**
 * 
 * @export
 * @interface OrderBracketsOut
 */
export interface OrderBracketsOut {
    /**
     * 
     * @type {Array<BracketOut>}
     * @memberof OrderBracketsOut
     */
    brackets?: Array<BracketOut>;
}

/**
 * Check if a given object implements the OrderBracketsOut interface.
 */
export function instanceOfOrderBracketsOut(value: object): value is OrderBracketsOut {
    return true;
}

export function OrderBracketsOutFromJSON(json: any): OrderBracketsOut {
    return OrderBracketsOutFromJSONTyped(json, false);
}

export function OrderBracketsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderBracketsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'brackets': json['brackets'] == null ? undefined : ((json['brackets'] as Array<any>).map(BracketOutFromJSON)),
    };
}

export function OrderBracketsOutToJSON(value?: OrderBracketsOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'brackets': value['brackets'] == null ? undefined : ((value['brackets'] as Array<any>).map(BracketOutToJSON)),
    };
}

