/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderHDRMerge
 */
export interface OrderHDRMerge {
    /**
     * The version of the AI model to use for enhancing the image.
     * @type {string}
     * @memberof OrderHDRMerge
     */
    aiVersion?: string;
    /**
     * The amount of brightness boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof OrderHDRMerge
     */
    brightnessBoost?: OrderHDRMergeBrightnessBoostEnum;
    /**
     * The amount of external brightness boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof OrderHDRMerge
     */
    brightnessBoostExternal?: OrderHDRMergeBrightnessBoostExternalEnum;
    /**
     * The amount of external brightness boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof OrderHDRMerge
     */
    brightnessBoostInternal?: OrderHDRMergeBrightnessBoostInternalEnum;
    /**
     * The amount of clarity to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof OrderHDRMerge
     */
    clarityLevel?: OrderHDRMergeClarityLevelEnum;
    /**
     * The type of clouds in the new sky to replace the original sky with. Options include: CLEAR, LOW_CLOUD, HIGH_CLOUD
     * @type {string}
     * @memberof OrderHDRMerge
     */
    cloudType?: OrderHDRMergeCloudTypeEnum;
    /**
     * The amount of contrast boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof OrderHDRMerge
     */
    contrastBoost?: OrderHDRMergeContrastBoostEnum;
    /**
     * The amount of external contrast boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof OrderHDRMerge
     */
    contrastBoostExternal?: OrderHDRMergeContrastBoostExternalEnum;
    /**
     * The amount of internal contrast boost to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof OrderHDRMerge
     */
    contrastBoostInternal?: OrderHDRMergeContrastBoostInternalEnum;
    /**
     * The amount of denoising to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof OrderHDRMerge
     */
    denoiseLevel?: OrderHDRMergeDenoiseLevelEnum;
    /**
     * Whether to enhance the image.
     * @type {boolean}
     * @memberof OrderHDRMerge
     */
    enhance?: boolean;
    /**
     * The type of enhancement to apply to the image. PROPERTY or PROPERTY_USA is used with AI version < 4.0, for >= 4.0 use WARM, NEUTRAL, or AUTHENTIC.
     * @type {string}
     * @memberof OrderHDRMerge
     */
    enhanceType?: OrderHDRMergeEnhanceTypeEnum;
    /**
     * Correct any lens distortion in the image.
     * @type {boolean}
     * @memberof OrderHDRMerge
     */
    lensCorrection?: boolean;
    /**
     * If provided then group into an image after every specified number of brackets, if  not provided or set to 0 then we automatically group based on visual analysis.
     * @type {number}
     * @memberof OrderHDRMerge
     */
    numberOfBracketsPerImage?: number;
    /**
     * Whether to blur any faces or license plates in the image.
     * @type {boolean}
     * @memberof OrderHDRMerge
     */
    privacy?: boolean;
    /**
     * The amount of saturation to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof OrderHDRMerge
     */
    saturationLevel?: OrderHDRMergeSaturationLevelEnum;
    /**
     * The amount of sharpening to apply to the image. Options include: NONE, LOW, MEDIUM, HIGH
     * @type {string}
     * @memberof OrderHDRMerge
     */
    sharpenLevel?: OrderHDRMergeSharpenLevelEnum;
    /**
     * Enable the replacement of the original sky for a summer sky.
     * @type {boolean}
     * @memberof OrderHDRMerge
     */
    skyReplacement?: boolean;
    /**
     * Correct any vertical distortion in the image so that it appears straight.
     * @type {boolean}
     * @memberof OrderHDRMerge
     */
    verticalCorrection?: boolean;
    /**
     * Whether to pull the windows in the image (used with AI version >= 4.0).
     * @type {boolean}
     * @memberof OrderHDRMerge
     */
    windowPull?: boolean;
}


/**
 * @export
 */
export const OrderHDRMergeBrightnessBoostEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type OrderHDRMergeBrightnessBoostEnum = typeof OrderHDRMergeBrightnessBoostEnum[keyof typeof OrderHDRMergeBrightnessBoostEnum];

/**
 * @export
 */
export const OrderHDRMergeBrightnessBoostExternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type OrderHDRMergeBrightnessBoostExternalEnum = typeof OrderHDRMergeBrightnessBoostExternalEnum[keyof typeof OrderHDRMergeBrightnessBoostExternalEnum];

/**
 * @export
 */
export const OrderHDRMergeBrightnessBoostInternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type OrderHDRMergeBrightnessBoostInternalEnum = typeof OrderHDRMergeBrightnessBoostInternalEnum[keyof typeof OrderHDRMergeBrightnessBoostInternalEnum];

/**
 * @export
 */
export const OrderHDRMergeClarityLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type OrderHDRMergeClarityLevelEnum = typeof OrderHDRMergeClarityLevelEnum[keyof typeof OrderHDRMergeClarityLevelEnum];

/**
 * @export
 */
export const OrderHDRMergeCloudTypeEnum = {
    Clear: 'CLEAR',
    LowCloud: 'LOW_CLOUD',
    HighCloud: 'HIGH_CLOUD',
    Null: 'null'
} as const;
export type OrderHDRMergeCloudTypeEnum = typeof OrderHDRMergeCloudTypeEnum[keyof typeof OrderHDRMergeCloudTypeEnum];

/**
 * @export
 */
export const OrderHDRMergeContrastBoostEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type OrderHDRMergeContrastBoostEnum = typeof OrderHDRMergeContrastBoostEnum[keyof typeof OrderHDRMergeContrastBoostEnum];

/**
 * @export
 */
export const OrderHDRMergeContrastBoostExternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type OrderHDRMergeContrastBoostExternalEnum = typeof OrderHDRMergeContrastBoostExternalEnum[keyof typeof OrderHDRMergeContrastBoostExternalEnum];

/**
 * @export
 */
export const OrderHDRMergeContrastBoostInternalEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type OrderHDRMergeContrastBoostInternalEnum = typeof OrderHDRMergeContrastBoostInternalEnum[keyof typeof OrderHDRMergeContrastBoostInternalEnum];

/**
 * @export
 */
export const OrderHDRMergeDenoiseLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type OrderHDRMergeDenoiseLevelEnum = typeof OrderHDRMergeDenoiseLevelEnum[keyof typeof OrderHDRMergeDenoiseLevelEnum];

/**
 * @export
 */
export const OrderHDRMergeEnhanceTypeEnum = {
    Property: 'property',
    PropertyUsa: 'property_usa',
    Warm: 'warm',
    Neutral: 'neutral',
    Authentic: 'authentic'
} as const;
export type OrderHDRMergeEnhanceTypeEnum = typeof OrderHDRMergeEnhanceTypeEnum[keyof typeof OrderHDRMergeEnhanceTypeEnum];

/**
 * @export
 */
export const OrderHDRMergeSaturationLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type OrderHDRMergeSaturationLevelEnum = typeof OrderHDRMergeSaturationLevelEnum[keyof typeof OrderHDRMergeSaturationLevelEnum];

/**
 * @export
 */
export const OrderHDRMergeSharpenLevelEnum = {
    None: 'NONE',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Null: 'null'
} as const;
export type OrderHDRMergeSharpenLevelEnum = typeof OrderHDRMergeSharpenLevelEnum[keyof typeof OrderHDRMergeSharpenLevelEnum];


/**
 * Check if a given object implements the OrderHDRMerge interface.
 */
export function instanceOfOrderHDRMerge(value: object): value is OrderHDRMerge {
    return true;
}

export function OrderHDRMergeFromJSON(json: any): OrderHDRMerge {
    return OrderHDRMergeFromJSONTyped(json, false);
}

export function OrderHDRMergeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderHDRMerge {
    if (json == null) {
        return json;
    }
    return {
        
        'aiVersion': json['ai_version'] == null ? undefined : json['ai_version'],
        'brightnessBoost': json['brightness_boost'] == null ? undefined : json['brightness_boost'],
        'brightnessBoostExternal': json['brightness_boost_external'] == null ? undefined : json['brightness_boost_external'],
        'brightnessBoostInternal': json['brightness_boost_internal'] == null ? undefined : json['brightness_boost_internal'],
        'clarityLevel': json['clarity_level'] == null ? undefined : json['clarity_level'],
        'cloudType': json['cloud_type'] == null ? undefined : json['cloud_type'],
        'contrastBoost': json['contrast_boost'] == null ? undefined : json['contrast_boost'],
        'contrastBoostExternal': json['contrast_boost_external'] == null ? undefined : json['contrast_boost_external'],
        'contrastBoostInternal': json['contrast_boost_internal'] == null ? undefined : json['contrast_boost_internal'],
        'denoiseLevel': json['denoise_level'] == null ? undefined : json['denoise_level'],
        'enhance': json['enhance'] == null ? undefined : json['enhance'],
        'enhanceType': json['enhance_type'] == null ? undefined : json['enhance_type'],
        'lensCorrection': json['lens_correction'] == null ? undefined : json['lens_correction'],
        'numberOfBracketsPerImage': json['number_of_brackets_per_image'] == null ? undefined : json['number_of_brackets_per_image'],
        'privacy': json['privacy'] == null ? undefined : json['privacy'],
        'saturationLevel': json['saturation_level'] == null ? undefined : json['saturation_level'],
        'sharpenLevel': json['sharpen_level'] == null ? undefined : json['sharpen_level'],
        'skyReplacement': json['sky_replacement'] == null ? undefined : json['sky_replacement'],
        'verticalCorrection': json['vertical_correction'] == null ? undefined : json['vertical_correction'],
        'windowPull': json['window_pull'] == null ? undefined : json['window_pull'],
    };
}

export function OrderHDRMergeToJSON(value?: OrderHDRMerge | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ai_version': value['aiVersion'],
        'brightness_boost': value['brightnessBoost'],
        'brightness_boost_external': value['brightnessBoostExternal'],
        'brightness_boost_internal': value['brightnessBoostInternal'],
        'clarity_level': value['clarityLevel'],
        'cloud_type': value['cloudType'],
        'contrast_boost': value['contrastBoost'],
        'contrast_boost_external': value['contrastBoostExternal'],
        'contrast_boost_internal': value['contrastBoostInternal'],
        'denoise_level': value['denoiseLevel'],
        'enhance': value['enhance'],
        'enhance_type': value['enhanceType'],
        'lens_correction': value['lensCorrection'],
        'number_of_brackets_per_image': value['numberOfBracketsPerImage'],
        'privacy': value['privacy'],
        'saturation_level': value['saturationLevel'],
        'sharpen_level': value['sharpenLevel'],
        'sky_replacement': value['skyReplacement'],
        'vertical_correction': value['verticalCorrection'],
        'window_pull': value['windowPull'],
    };
}

