/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderIn
 */
export interface OrderIn {
    /**
     * The ID for the order.
     * @type {string}
     * @memberof OrderIn
     */
    orderId?: string;
    /**
     * The name for the order.
     * @type {string}
     * @memberof OrderIn
     */
    name?: string;
}

/**
 * Check if a given object implements the OrderIn interface.
 */
export function instanceOfOrderIn(value: object): boolean {
    return true;
}

export function OrderInFromJSON(json: any): OrderIn {
    return OrderInFromJSONTyped(json, false);
}

export function OrderInFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderIn {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OrderInToJSON(value?: OrderIn | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'order_id': value['orderId'],
        'name': value['name'],
    };
}

