/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';
import type { OrderOut } from './OrderOut';
import {
    OrderOutFromJSON,
    OrderOutFromJSONTyped,
    OrderOutToJSON,
} from './OrderOut';

/**
 * 
 * @export
 * @interface OrdersOut
 */
export interface OrdersOut {
    /**
     * 
     * @type {Array<OrderOut>}
     * @memberof OrdersOut
     */
    orders?: Array<OrderOut>;
    /**
     * 
     * @type {Pagination}
     * @memberof OrdersOut
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the OrdersOut interface.
 */
export function instanceOfOrdersOut(value: object): value is OrdersOut {
    return true;
}

export function OrdersOutFromJSON(json: any): OrdersOut {
    return OrdersOutFromJSONTyped(json, false);
}

export function OrdersOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrdersOut {
    if (json == null) {
        return json;
    }
    return {
        
        'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(OrderOutFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function OrdersOutToJSON(value?: OrdersOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(OrderOutToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

