/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderOut } from './OrderOut';
import {
    OrderOutFromJSON,
    OrderOutFromJSONTyped,
    OrderOutToJSON,
} from './OrderOut';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';

/**
 * 
 * @export
 * @interface OrdersOut
 */
export interface OrdersOut {
    /**
     * 
     * @type {Array<OrderOut>}
     * @memberof OrdersOut
     */
    orders?: Array<OrderOut>;
    /**
     * 
     * @type {Pagination}
     * @memberof OrdersOut
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the OrdersOut interface.
 */
export function instanceOfOrdersOut(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrdersOutFromJSON(json: any): OrdersOut {
    return OrdersOutFromJSONTyped(json, false);
}

export function OrdersOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrdersOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orders': !exists(json, 'orders') ? undefined : ((json['orders'] as Array<any>).map(OrderOutFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function OrdersOutToJSON(value?: OrdersOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orders': value.orders === undefined ? undefined : ((value.orders as Array<any>).map(OrderOutToJSON)),
        'pagination': PaginationToJSON(value.pagination),
    };
}

