/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderIn
 */
export interface OrderIn {
    /**
     * The ID for the order.
     * @type {string}
     * @memberof OrderIn
     */
    orderId?: string;
    /**
     * The name for the order.
     * @type {string}
     * @memberof OrderIn
     */
    name?: string;
}

/**
 * Check if a given object implements the OrderIn interface.
 */
export function instanceOfOrderIn(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderInFromJSON(json: any): OrderIn {
    return OrderInFromJSONTyped(json, false);
}

export function OrderInFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderId': !exists(json, 'order_id') ? undefined : json['order_id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function OrderInToJSON(value?: OrderIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order_id': value.orderId,
        'name': value.name,
    };
}

