/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationErrorDetailLocation } from './ValidationErrorDetailLocation';
import {
    ValidationErrorDetailLocationFromJSON,
    ValidationErrorDetailLocationFromJSONTyped,
    ValidationErrorDetailLocationToJSON,
} from './ValidationErrorDetailLocation';

/**
 * 
 * @export
 * @interface ValidationErrorDetail
 */
export interface ValidationErrorDetail {
    /**
     * 
     * @type {ValidationErrorDetailLocation}
     * @memberof ValidationErrorDetail
     */
    location?: ValidationErrorDetailLocation;
}

/**
 * Check if a given object implements the ValidationErrorDetail interface.
 */
export function instanceOfValidationErrorDetail(value: object): boolean {
    return true;
}

export function ValidationErrorDetailFromJSON(json: any): ValidationErrorDetail {
    return ValidationErrorDetailFromJSONTyped(json, false);
}

export function ValidationErrorDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'location': json['&lt;location&gt;'] == null ? undefined : ValidationErrorDetailLocationFromJSON(json['&lt;location&gt;']),
    };
}

export function ValidationErrorDetailToJSON(value?: ValidationErrorDetail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '&lt;location&gt;': ValidationErrorDetailLocationToJSON(value['location']),
    };
}

