/* tslint:disable */
/* eslint-disable */
/**
 * Autoenhance API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorDetailLocation
 */
export interface ValidationErrorDetailLocation {
    /**
     * 
     * @type {Array<string>}
     * @memberof ValidationErrorDetailLocation
     */
    fieldName?: Array<string>;
}

/**
 * Check if a given object implements the ValidationErrorDetailLocation interface.
 */
export function instanceOfValidationErrorDetailLocation(value: object): value is ValidationErrorDetailLocation {
    return true;
}

export function ValidationErrorDetailLocationFromJSON(json: any): ValidationErrorDetailLocation {
    return ValidationErrorDetailLocationFromJSONTyped(json, false);
}

export function ValidationErrorDetailLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorDetailLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'fieldName': json['&lt;field_name&gt;'] == null ? undefined : json['&lt;field_name&gt;'],
    };
}

export function ValidationErrorDetailLocationToJSON(value?: ValidationErrorDetailLocation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '&lt;field_name&gt;': value['fieldName'],
    };
}

