name: JavaScript

on:
  push:
    branches:
      - main
      
defaults:
  run:
   working-directory: ./javascript/package.json
jobs:
  publish:
    name: Publish NPM Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: npm install

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
